version: "3.8"
services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ranode-app
  nginix:
    image: nginx:alpine
    ports:
      - 5001:80
      - 5000:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/ssl/:/etc/nginx/ssl/
      - /var/lib/docker/volumes/ra/_data/files:/app/files
    env_file:
       - ./.env.production