server {
        listen 80 default_server;
        listen 443 ssl;
        listen [::]:443 ssl;
#       root   /usr/share/nginx/html;
        server_name invalumetrics.online www.invalumetrics.online;
#       index index.html index.php index.htm index.nginx-debian.html;
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;
   location / {
#try_files $uri $uri/ /index.html;
proxy_pass http://ranode-app:5000;
 #     proxy_http_version 1.1;
  #    proxy_set_header Upgrade $http_upgrade;
   #   proxy_set_header Connection 'upgrade';
    #  proxy_set_header Host $host;
     # proxy_cache_bypass $http_upgrade;
    }
}
